entryPoints:
web:
address: ":80"
websecure:
address: ":443"


providers:
docker:
endpoint: "unix:///var/run/docker.sock"
exposedByDefault: false


certificatesResolvers:
myresolver:
acme:
email: you@example.com
storage: /acme/acme.json
tlsChallenge: {}


api:
dashboard: true